# name: Deploy to EC2

# on:
#   workflow_run:
#     workflows:
#       - "Buid and Push Docker Image"
#     types:
#       - completed

# env:
#   IMAGE_NAME: cc-web-tier-controller

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Deploy to EC2
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.EC2_USERNAME }}
#           key: ${{ secrets.EC2_SSH_KEY }}
#           script: |
#             docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
#             docker stop web-tier || true
#             docker rm web-tier || true
#             docker run -d \
#               --name web-tier \
#               -p 8000:8000 \
#               -e FLASK_APP=server.py \
#               -e aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }} \
#               -e aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
#               -e region_name=${{ secrets.AWS_REGION }} \
#               ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest